create migration and seeder
st-vienhuynh/laravel-intern-2111 pull request #3
Opened 2021-12-21 14:13 UTC by st-vienhuynh

2021-12-22 03:24 UTC, st-minhdao requested changes
Chưa thấy em làm phần practice của các câu query

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/app/Http/Controllers/TaskController.php
> +        $due_date = $request->due_date;
chỗ này sao giống Huy thế

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/app/Http/Controllers/TaskController.php
> +        return view('admin/task/details', ['value' => $value], ['id' => $id]);
sử dụng . thay cho / nha em
trong cái object task trả về là có id trong đó rồi mà hè, mình đâu cần gửi thêm biến id làm chi nữa

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/app/Http/Controllers/TaskController.php
> +        $value = DB::table('task')->find($id);
đặt lại tên biến cho rõ nghĩa $task

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/app/Http/Controllers/TaskController.php
> +        return view('admin/task/edit', ['value' => $value], ['id' => $id]);
tương tự comment trên

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/app/Http/Controllers/TaskController.php
> +        $due_date = $request->due_date;
lại giống

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/database/migrations/2021_12_21_081307_create_tasks_table.php
> +        Schema::create('task', function (Blueprint $table) {
bảng tasks chớ ko phải là task nha Viễn

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/database/migrations/2021_12_21_081307_create_tasks_table.php
> +            $table->string('description')->nullable();
cái ni dài thì nên dùng `text`

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/database/migrations/2021_12_21_081307_create_tasks_table.php
> +            $table->integer('status')->nullable();
dùng kiểu dữ liệu nhỏ hơn, và là số dương

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/resources/views/admin/task/details.blade.php
> +                <form action="{{url('/tasks/'.$id)}}" method="post">
dùng route name để truyền vào

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/resources/views/admin/task/edit.blade.php
> +                            <form action="{{url('/tasks/'.$value->id)}}" method="post" enctype="multipart/form-data" class="form-horizontal form-material">
dùng route name

2021-12-22 03:24 UTC, st-minhdao commented on laravel_training/resources/views/admin/task/index.blade.php
> +                <form action="{{url('/tasks/'.$value->id)}}" method="post">
route name

2021-12-22 04:42 UTC, st-trampham commented on laravel_training/app/Http/Controllers/TaskController.php
>          return view('admin/task/index', ['value' => $value]);
Chỗ này sửa laị dùng dấu `.` thay `/` nè em

2021-12-23 02:41 UTC, st-minhdao approved these changes

2021-12-23 02:41 UTC, merged